### PR TITLE
Add krb5_cc_set_config() and krb5_cc_get_config()

### PR DESCRIPTION
**Pull request by steffen-kiess**

### CODE REVIEW

**Comment by jborean93** [comment]
Looks like I need to fix up CI, I'll ping you when it is so you can rebase your changes and pull it though. Sorry about that.

**Comment by jborean93** [comment]
PR has been pushed which should fix things.

**Comment by steffen-kiess** [comment]
Ok, I've rebased the pull requests.

**Review by jborean93 — APPROVED** [review]
Looks great, thanks for the quality PR

**Pull request merged**
